In [46]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression,LogisticRegression
import seaborn as sb
import matplotlib.pyplot as mp
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [26]:
df = pd.read_csv('Social_Network_ads.csv')

In [27]:
df.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [28]:
df.tail(10)

User ID  Gender  Age  EstimatedSalary  Purchased
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [29]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [31]:
df.shape

(400, 5)

In [50]:
x = df.loc[:,['Age','EstimatedSalary']].values


In [49]:
y = df['Purchased']


In [179]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=20,random_state=42)

In [180]:
sc = StandardScaler()

In [181]:
lr = LogisticRegression()

In [182]:
lr.fit(x_train,y_train)

LogisticRegression()

In [183]:
y_predict = lr.predict(x_test)

In [184]:
x_train = sc.fit_transform(x_train)

In [185]:
x_test = sc.transform(x_test)

In [186]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [187]:
sk = np.vstack([y_predict,y_test]).T
sk

array([[0, 0],
       [0, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1]], dtype=int64)

In [188]:
sk[:10,:]

array([[0, 0],
       [0, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [189]:
from sklearn.metrics import confusion_matrix

In [190]:
cm= confusion_matrix(y_test,y_predict)
cm

array([[14,  0],
       [ 6,  0]], dtype=int64)

In [191]:
TP=cm[1,1]
TP

0

In [192]:
TN=cm[1,0]
TN

6

In [193]:
FP=cm[0,1]
FP

0

In [194]:
FN = cm[0,0]
FN

14

In [195]:
pr= TP/(TP + FP)
pr

C:\Users\student\AppData\Local\Temp\ipykernel_1848\1186158155.py:1: RuntimeWarning: invalid value encountered in scalar divide
  pr= TP/(TP + FP)


nan

In [196]:
rc=TP/(TP+FN)
rc

0.0

In [197]:
acc=(TP+TN)/(TP+TN+FP+FN)
acc

0.3

In [198]:
er = 100 - acc
er

99.7